# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            SAC
tagline:          'StandAloneComplex'
description:      'Visible Non Abstract'
url:              http://wajatimur.github.io
baseurl:          /

author:
  name:           'Azri Jamil'
  url:            https://twitter.com/azrijamil

paginate:         5

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/wajatimur/wajatimur.github.io

plugins:   
  - jekyll-paginate   
  - redcarpet   
  - jekyll-gist   
  - pygments.rb
  - wdm
